### ISSUE TITLE
Usage in Dynamo out-of-the-box

### ISSUE THREAD

**Issue by Amoursol** [alfarok/NodeModelCharts#3]
Hi @alfarok 👋 long time man! 

We are looking to get Charts put into Dynamo out of the box now with a contractor, and we're thinking of consuming your NodeModelCharts package and making some minor tweaks. Are you OK with us doing this? 

Cheers,
Sol

**Comment by alfarok** [comment]
It's disappointing that the work wasn't acknowledged 3 years ago when it was created and now a 3rd party is being paid to copy an open source repo instead of contributing to the original package but the [license](https://github.com/alfarok/NodeModelCharts/blob/master/LICENSE) is MIT so ¯\\_(ツ)_/¯
